### ISSUE TITLE
Rediseño opción de configuraciones del sistema

### ISSUE THREAD

**Issue by didierymartinez** [SincosoftSAS/Bitakora#15]
Diseño completamente nuevo de las configuraciones del sistema por empresa de Bitákora, ahora un panel izquierdo agrupa los tipos de configuración para que la visualización sea mas amigable y fácil de navegar.

**Comment by luisfelipediaz** [comment]
- [x] Diseño en figma
- [x] Desarrollo
- [x] Publicado
